spring:
  servlet:
    multipart:
      max-file-size: 3MB
  jwt:
    issuer: dev
    secret: dev
    access-expiration: 1800000
    refresh-expiration: 10800000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: dev
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver