spring:
  servlet:
    multipart:
      max-file-size: 3MB
  jwt:
    issuer: safepp
    secret: EfEcxwAxYfNVDcas412ASDAcxdwdqdqw123csDASDWQqweasddasac
    access-expiration: 1800000
    refresh-expiration: 10800000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://34.158.195.47:3306/travel_db?serverTimezone=Asia/Seoul&useSSL=false
    username: user
    password: Kjs31129@
    driver-class-name: com.mysql.cj.jdbc.Driver
